/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/revenue/snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest revenue snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RevenueSnapshotLatest"];
                    };
                };
                /** @description Snapshot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RevenueSnapshotMissing"];
                    };
                };
                /** @description API error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonValue: string | number | boolean | null | components["schemas"]["JsonValue"][] | {
            [key: string]: components["schemas"]["JsonValue"];
        };
        RevenueSnapshotLatest: {
            snapshot_id: string;
            generated_at: string;
            total_exposure_cents: number;
            expected_recovery_30_day_cents: number;
            short_term_cash_opportunity_cents: number;
            high_risk_claim_count: number;
            critical_pre_submission_count: number;
            top_aggressive_payers: components["schemas"]["JsonValue"][];
            top_revenue_loss_drivers: components["schemas"]["JsonValue"][];
            top_worklist: components["schemas"]["JsonValue"][];
        };
        RevenueSnapshotMissing: {
            /** @enum {string} */
            error: "snapshot_not_found";
            detail?: components["schemas"]["JsonValue"];
            message?: string;
        };
        ApiErrorResponse: {
            error: string;
            detail?: components["schemas"]["JsonValue"];
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
