# SQLite test compatibility shims (safe no-op for Postgres).
from app.db import sqlite_compat  # noqa: F401

# Import models here so SQLAlchemy registers them with Base.metadata
from app.db.models.audit_event import AuditEvent  # noqa: F401
from app.db.models.analytics_ai_audit_log import AnalyticsAiAuditLog  # noqa: F401
from app.db.models.analytics_alert import AnalyticsAlert  # noqa: F401
from app.db.models.analytics_metric import AnalyticsMetric  # noqa: F401
from app.db.models.bi_report import BIReport  # noqa: F401
from app.db.models.billed_line import BilledLine  # noqa: F401
from app.db.models.ai_message import AiMessage  # noqa: F401
from app.db.models.ai_thread import AiThread  # noqa: F401
from app.db.models.assistant_memory_item import AssistantMemoryItem  # noqa: F401
from app.db.models.assistant_notification import AssistantNotification  # noqa: F401
from app.db.models.assistant_reminder import AssistantReminder  # noqa: F401
from app.db.models.announcement import Announcement  # noqa: F401
from app.db.models.clinical_audit_finding import ClinicalAuditFinding  # noqa: F401
from app.db.models.clinical_audit_run import ClinicalAuditRun  # noqa: F401
from app.db.models.call_disposition import CallDisposition  # noqa: F401
from app.db.models.call_event import CallEvent  # noqa: F401
from app.db.models.disclosure_log import DisclosureLog  # noqa: F401
from app.db.models.document import Document  # noqa: F401
from app.db.models.encounter import Encounter  # noqa: F401
from app.db.models.event_outbox import EventOutbox  # noqa: F401
from app.db.models.era_line import EraLine  # noqa: F401
from app.db.models.form_submission import FormSubmission  # noqa: F401
from app.db.models.form_template import FormTemplate  # noqa: F401
from app.db.models.generated_report import GeneratedReport  # noqa: F401
from app.db.models.integration_account import IntegrationAccount  # noqa: F401
from app.db.models.integration_token import IntegrationToken  # noqa: F401
from app.db.models.user_microsoft_connection import UserMicrosoftConnection  # noqa: F401
from app.db.models.invite import Invite  # noqa: F401
from app.db.models.live_call import LiveCall  # noqa: F401
from app.db.models.organization import Organization  # noqa: F401
from app.db.models.organization_membership import OrganizationMembership  # noqa: F401
from app.db.models.organization_role import OrganizationRole  # noqa: F401
from app.db.models.organization_role_permission import OrganizationRolePermission  # noqa: F401
from app.db.models.organization_tile import OrganizationTile  # noqa: F401
from app.db.models.organization_tile_node import OrganizationTileNode  # noqa: F401
from app.db.models.patient import Patient  # noqa: F401
from app.db.models.episode_of_care import EpisodeOfCare  # noqa: F401
from app.db.models.patient_care_team import PatientCareTeam  # noqa: F401
from app.db.models.patient_document import PatientDocument  # noqa: F401
from app.db.models.patient_note import PatientNote  # noqa: F401
from app.db.models.patient_requirement import PatientRequirement  # noqa: F401
from app.db.models.patient_service_enrollment import PatientServiceEnrollment  # noqa: F401
from app.db.models.patient_treatment_stage import PatientTreatmentStage  # noqa: F401
from app.db.models.patient_treatment_stage_event import PatientTreatmentStageEvent  # noqa: F401
from app.db.models.password_reset_token import PasswordResetToken  # noqa: F401
from app.db.models.portal_access_code import PortalAccessCode  # noqa: F401
from app.db.models.review_action import ReviewAction  # noqa: F401
from app.db.models.review_evidence_link import ReviewEvidenceLink  # noqa: F401
from app.db.models.review_queue_item import ReviewQueueItem  # noqa: F401
from app.db.models.ringcentral_event import RingCentralEvent  # noqa: F401
from app.db.models.ringcentral_credential import RingCentralCredential  # noqa: F401
from app.db.models.ringcentral_subscription import RingCentralSubscription  # noqa: F401
from app.db.models.reception_call_workflow import ReceptionCallWorkflow  # noqa: F401
from app.db.models.recon_claim_result import ReconClaimResult  # noqa: F401
from app.db.models.recon_import_job import ReconImportJob  # noqa: F401
from app.db.models.recon_line_result import ReconLineResult  # noqa: F401
from app.db.models.claim import Claim  # noqa: F401
from app.db.models.claim_line import ClaimLine  # noqa: F401
from app.db.models.claim_event import ClaimEvent  # noqa: F401
from app.db.models.claim_ledger import ClaimLedger  # noqa: F401
from app.db.models.rpt_kpi_daily import RptKpiDaily  # noqa: F401
from app.db.models.rpt_kpi_snapshot import RptKpiSnapshot  # noqa: F401
from app.db.models.revenue_command_snapshot import RevenueCommandSnapshot  # noqa: F401
from app.db.models.service import Service  # noqa: F401
from app.db.models.service_document_template import ServiceDocumentTemplate  # noqa: F401
from app.db.models.task import Task  # noqa: F401
from app.db.models.user import User  # noqa: F401
from app.db.models.user_preference import UserPreference  # noqa: F401
from app.db.models.scribe_capture import ScribeCapture  # noqa: F401
from app.db.models.scribe_note_draft import ScribeNoteDraft  # noqa: F401
from app.db.models.scribe_transcript import ScribeTranscript  # noqa: F401
from app.db.models.webhook_delivery import WebhookDelivery  # noqa: F401
from app.db.models.webhook_endpoint import WebhookEndpoint  # noqa: F401
from app.db.models.document_analysis import DocumentAnalysis  # noqa: F401
from app.db.models.pdf_template_registry import PdfTemplateRegistry  # noqa: F401
